### ISSUE TITLE
Any simple sample for AWS Sagemaker

### ISSUE THREAD

**Issue by ponnou** [aws-samples/aws-sagemaker-build#1]
Hello,

I am a beginner with CloudFormation, I am trying to generate an instance of AWS Sagemaker via CloudFormation, do you have any simple template (to start) ?   

Thank you,
Andre

**Comment by JohnCalhoun** [comment]
hey andre,
yes, this repository should provide you a good example,
clone the repo,
follow the instructions in the README.md to build the template and then launch it
