### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by C24IO** [aws-samples/aws-sagemaker-build#14]
getTrainingConfig - this Lambda is failing. 

2018-10-18T00:55:46.691Z	7ef43ae0-37df-4897-8d46-2184666fbfb8
{
    "errorMessage": "TypeError: Cannot read property '1' of null",
    "errorType": "Error",
    "stackTrace": [
        "exports.handler (/var/task/index.js:57:18)"
    ]
}

**Comment by JohnCalhoun** [comment]
this should be fixed, re open if you see it again
