### ISSUE TITLE
Add Tags Support

### ISSUE THREAD

**Issue by oelesinsc24** [aws-samples/aws-sagemaker-build#21]

**Comment by JohnCalhoun** [comment]
how are you imaging this work. Would you want tags to propagate to all created resources (jobs, models, endpoints) or be specific to each resource. could you also explain why you need tagging support

**Comment by oelesinsc24** [comment]
Thanks for the prompt response @JohnCalhoun. I would like to tag the created resources. Example would be to identify the cost allocation for each job, model and endpoint.

Thanks in advance
