### ISSUE TITLE
Unable to Pull SciKit Learn Image

### ISSUE THREAD

**Issue by oelesinsc24** [aws-samples/aws-sagemaker-build#25]
When training a Scikit Learn model, I get this error: `ClientError: Cannot pull algorithm container. Either the image does not exist or its permissions are incorrect.`.

On investigating I discovered that the image: `683313688378.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3` does not exist in EU_WEST_1 region.

Further checks reveal that there are two ways to collect scikit learn images:
1. https://github.com/aws-samples/aws-sagemaker-build/blob/5a16995af6fcf8ac12caa56f55f287ba0b288754/lambda/util/nodejs/lib/CreateImageURI.js#L9-L28
2. https://github.com/aws-samples/aws-sagemaker-build/blob/5a16995af6fcf8ac12caa56f55f287ba0b288754/lambda/util/nodejs/lib/CreateImageURI.js#L30-L34

However, #L9-L28 actually refers to chainer. Maybe some error there. 

Would be great if you could help fix this.

Impressive work!!! 👍

**Comment by JohnCalhoun** [comment]
looking into this now

**Comment by JohnCalhoun** [comment]
can you verify this fixes your problem

**Comment by oelesinsc24** [comment]
Giving it a try now.

**Comment by oelesinsc24** [comment]
This is resolved. Trained a model and deployed a Scikit Learn endpoint on SageMaker

Yohooo!!

Thanks
