### ISSUE TITLE
Race condition between inference image and training 

### ISSUE THREAD

**Issue by C24IO** [aws-samples/aws-sagemaker-build#7]
All things being equal, after a few clean runs of the excellent utility, it seems that there is a race condition. Between inference image build and training. As the first invocation of build inference image, fails always. Second invocation after completing the training of the model, it succeeds. Possible race issue, but don’t have proof right now. But still worth looking at.

**Comment by JohnCalhoun** [comment]
what is the status of this?

**Comment by C24IO** [comment]
Checking if its still there in the latest version.

**Comment by JohnCalhoun** [comment]
closing, assuming this is fixed, re open if this shows up again
